let en = {
    // GDPR
    gdpr: {
        gdprParagraph : 'We use cookies to improve your experience on this site. By continuing, you accept our privacy policy.',
        gdprLink : 'More Details',
        gdprButton : 'Agree',
    },

    // SIDEBAR MENU
    menu: {
        closeButton: 'Close',
        artworksButton: 'Artworks',
        displayAllButton: 'All',
        displayStructuralCollageButton: 'Structural Collage',
        displayInteriorButton: 'Interior',
        exhibitionButton: 'Exhibitions',
        biographyButton: 'Biography',
        contactButton: 'Contact',
        // used only in artworkitem
        backToMainPage: 'Back',
    },

    // ARTWORKS
    artworks: {
        '0062': {
            metaTitle: 'Toxic',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Toxic',
            paintingUrlNum: '0062',
            paintingDataTitle: 'Toxic',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '70 cm',
            paintingDimensionsHeight: '100 cm',
            paintingYearOfCreation: '2020',    
            paintingTitle: 'Toxic',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca symbolizuje „coś” toksycznego, trującego, substancję która budzi niepokój, zielony trujący gaz i jest czymś nieznanym, dzikim i nieodkrytym. Powoli wydobywa się na powierzchnię by opanować cały świat. Praca powstała pod wpływem narastającej epidemii COVID-19.',
            paintingImages: {
                '0062-1': 'images\0062\0062-1.jpg',
                '0062-2': 'images\0062\0062-2.jpg',
                '0062-3': 'images\0062\0062-3.jpg',
                '0062-4': 'images\0062\0062-4.jpg',
                '0062-5': 'images\0062\0062-5.jpg',
                '0062-6': 'images\0062\0062-6.jpg',
                '0062-7': 'images\0062\0062-7.jpg',
                '0062-8': 'images\0062\0062-8.jpg',
            }
        },

        '0061': {
            metaTitle: 'Hivé',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Hivé',
            paintingUrlNum: '0061',
            paintingDataTitle: 'Hivé',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '70 cm',
            paintingDimensionsHeight: '100 cm',
            paintingYearOfCreation: '2018',    
            paintingTitle: 'Hivé',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca wykonana w charakterze structural collage. Do jej wykonania posłużyła czarna plastikowa siatka przytwierdzona do płótna za pomocą specjalistycznego kleju zalana czarną olejną farbą. Symbolizuje, ul, społeczeństwo.',
            paintingImages: {
                '0061-1': 'images\0061\0061-1.jpg',
                '0061-2': 'images\0061\0061-2.jpg',
                '0061-3': 'images\0061\0061-3.jpg',
                '0061-4': 'images\0061\0061-4.jpg',
                '0061-5': 'images\0061\0061-5.jpg',
                '0061-6': 'images\0061\0061-6.jpg',
                '0061-7': 'images\0061\0061-7.jpg',
                '0061-8': 'images\0061\0061-8.jpg',
                '0061-9': 'images\0061\0061-9.jpg',
            }
        },

        '0060': {
            metaTitle: 'Freedom',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Freedom',
            paintingUrlNum: '0060',
            paintingDataTitle: 'Freedom',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '70 cm',
            paintingDimensionsHeight: '100 cm',
            paintingYearOfCreation: '2018',    
            paintingTitle: 'Freedom',
            paintingStatus: 'Available ',
            paintingDescription: 'Freedom: oznacza wolność artystyczną. Wolność poprzez zastosowanie różnych technik malarskich. Wolność w postaci abstrakcji artystycznej. Wolność w postaci otwartego umysłu na nowe. Wykonany z opiłków metalu przytwierdzonych za pomocą specjalistycznego kleju i grubo lanej farby. Obraz zamalowany po bokach nie wymaga ramy, sygnowany i podpisany na odwrocie.',
            paintingImages: {
                '0060-1': 'images\0060\0060-1.jpg',
                '0060-2': 'images\0060\0060-2.jpg',
                '0060-3': 'images\0060\0060-3.jpg',
                '0060-4': 'images\0060\0060-4.jpg',
                '0060-5': 'images\0060\0060-5.jpg',
                '0060-6': 'images\0060\0060-6.jpg',
                '0060-7': 'images\0060\0060-7.jpg',
                '0060-8': 'images\0060\0060-8.jpg',
                '0060-9': 'images\0060\0060-9.jpg',
            }
        },

        '0059': {
            metaTitle: 'Pink Teeth',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Pink Teeth',
            paintingUrlNum: '0059',
            paintingDataTitle: 'Pink Teeth',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '50 cm',
            paintingDimensionsHeight: '70 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Pink Teeth',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca z cyklu Interior nawiązująca do zdjęcia rentgenowskiego oraz wystawy Interior.',
            paintingImages: {
                '0059-1': 'images\0059\0059-1.jpg',
            }
        },

        '0058': {
            metaTitle: 'Green Teeth',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Green Teeth',
            paintingUrlNum: '0058',
            paintingDataTitle: 'Green Teeth',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '120 cm',
            paintingDimensionsHeight: '100 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Green Teeth',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca z cyklu Interior nawiązująca do zdjęcia rentgenowskiego oraz wystawy Interior.',
            paintingImages: {
                '0058-1': 'images\0058\0058-1.jpg',
            }
        },

        '0057': {
            metaTitle: 'Blue Teeth',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Blue Teeth',
            paintingUrlNum: '0057',
            paintingDataTitle: 'Blue Teeth',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '50 cm',
            paintingDimensionsHeight: '70 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Blue Teeth',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca z cyklu Interior nawiązująca do zdjęcia rentgenowskiego oraz wystawy Interior.',
            paintingImages: {
                '0057-1': 'images\0057\0057-1.jpg',
            }
        },

        '0056': {
            metaTitle: 'Dragon Flower',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Dragon Flower',
            paintingUrlNum: '0056',
            paintingDataTitle: 'Dragon Flower',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '',
            paintingDimensionsHeight: '50 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Dragon Flower',
            paintingStatus: 'Available ',
            paintingDescription: 'Instalacja artystyczna wykonana z papieru. Imitującą liście roślinne, przypominające jednocześnie smocze skrzydła i roślinę egzotyczną.',
            paintingImages: {
                '0056-1': 'images\0056\0056-1.jpg',
                '0056-2': 'images\0056\0056-2.jpg',
                '0056-3': 'images\0056\0056-3.jpg',
                '0056-4': 'images\0056\0056-4.jpg',
                '0056-5': 'images\0056\0056-5.jpg',
            }
        },

        '0055': {
            metaTitle: 'Space Brain',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Space Brain',
            paintingUrlNum: '0055',
            paintingDataTitle: 'Space Brain',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Space Brain',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca powstała w nawiązaniu do zdjęcia z rezonansu magnetycznego. Ukazując abstrakcyjnamą wizję mózgu. Będąc odniesieniem do cyklu Interior lecz z wykorzystaniem rezonansu magnetycznego.',
            paintingImages: {
                '0055-1': 'images\0055\0055-1.jpg',
                '0055-2': 'images\0055\0055-2.jpg',
            }
        },

        '0054': {
            metaTitle: 'Secret Brain',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Secret Brain',
            paintingUrlNum: '0054',
            paintingDataTitle: 'Secret Brain',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Secret Brain',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca powstała w nawiązaniu do zdjęcia z rezonansu magnetycznego. Ukazując abstrakcyjnamą wizję mózgu. Będąc odniesieniem do cyklu Interior lecz z wykorzystaniem rezonansu magnetycznego.',
            paintingImages: {
                '0054-1': 'images\0054\0054-1.jpg',
                '0054-2': 'images\0054\0054-2.jpg',
            }
        },

        '0053': {
            metaTitle: 'Golden Brain',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Golden Brain',
            paintingUrlNum: '0053',
            paintingDataTitle: 'Golden Brain',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Golden Brain',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca powstała w nawiązaniu do zdjęcia z rezonansu magnetycznego. Ukazując abstrakcyjnamą wizję mózgu. Będąc odniesieniem do cyklu Interior lecz z wykorzystaniem rezonansu magnetycznego.',
            paintingImages: {
                '0053-1': 'images\0053\0053-1.jpg',
                '0053-2': 'images\0053\0053-2.jpg',
            }
        },

        '0052': {
            metaTitle: 'Super Brain',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Super Brain',
            paintingUrlNum: '0052',
            paintingDataTitle: 'Super Brain',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Super Brain',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca powstała w nawiązaniu do zdjęcia z rezonansu magnetycznego. Ukazując abstrakcyjnamą wizję mózgu. Będąc odniesieniem do cyklu Interior lecz z wykorzystaniem rezonansu magnetycznego.',
            paintingImages: {
                '0052-1': 'images\0052\0052-1.jpg',
                '0052-2': 'images\0052\0052-2.jpg',
            }
        },

        '0051': {
            metaTitle: 'Alien',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Alien',
            paintingUrlNum: '0051',
            paintingDataTitle: 'Alien',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Alien',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca powstała inspirując się zdjęciem powstałym podczas badania rezonansem magnetycznym. W nawiązaniu do obcych.',
            paintingImages: {
                '0051-1': 'images\0051\0051-1.jpg',
                '0051-2': 'images\0051\0051-2.jpg',
            }
        },

        '0050': {
            metaTitle: 'Alarm',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Alarm',
            paintingUrlNum: '0050',
            paintingDataTitle: 'Alarm',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Alarm',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca powstała inspirując się zdjęciem powstałym podczas badania rezonansem magnetycznym. W nawiązaniu do obcych.',
            paintingImages: {
                '0050-1': 'images\0050\0050-1.jpg',
                '0050-2': 'images\0050\0050-2.jpg',
            }
        },

        '0049': {
            metaTitle: 'Interior Dog 1 / Interior Dog 2',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Interior Dog 1 / Interior Dog 2',
            paintingUrlNum: '0049',
            paintingDataTitle: 'Interior Dog 1 / Interior Dog 2',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '2 x 70 cm',
            paintingDimensionsHeight: '2 x 50 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Interior Dog 1 / Interior Dog 2',
            paintingStatus: 'Sprzedane',
            paintingDescription: 'Prace powstałe w wyniku inspiracji cyklem Interior nawiązując do zdjęcia rentgenowskiego psa.',
            paintingImages: {
                '0049-1': 'images\0049\0049-1.jpg',
                '0049-2': 'images\0049\0049-2.jpg',
                '0049-3': 'images\0049\0049-3.jpg',
                '0049-4': 'images\0049\0049-4.jpg',
            }
        },


        '0048': {
            metaTitle: 'Pinkterior',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Pinkterior',
            paintingUrlNum: '0048',
            paintingDataTitle: 'Pinkterior',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Pinkterior',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0048-1': 'images\0048\0048-1.jpg',
            }
        },

        '0047': {
            metaTitle: 'Lemon Brother Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Lemon Brother Skull',
            paintingUrlNum: '0047',
            paintingDataTitle: 'Lemon Brother Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Lemon Brother Skull',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0047-1': 'images\0047\0047-1.jpg',
            }
        },

        '0046': {
            metaTitle: 'Rainbow Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Rainbow Skull',
            paintingUrlNum: '0046',
            paintingDataTitle: 'Rainbow Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Rainbow Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0046-1': 'images\0046\0046-1.jpg',
            }
        },

        '0045': {
            metaTitle: 'Fire Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Fire Skull',
            paintingUrlNum: '0045',
            paintingDataTitle: 'Fire Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Fire Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0045-1': 'images\0045\0045-1.jpg',
            }
        },   

        '0044': {
            metaTitle: 'Disco Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Disco Skull',
            paintingUrlNum: '0044',
            paintingDataTitle: 'Disco Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Disco Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0044-1': 'images\0044\0044-1.jpg',
            }
        },

        '0043': {
            metaTitle: 'Earth Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Earth Skull',
            paintingUrlNum: '0043',
            paintingDataTitle: 'Earth Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Earth Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0043-1': 'images\0043\0043-1.jpg',
            }
        },

        '0042': {
            metaTitle: 'Copper Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Copper Skull',
            paintingUrlNum: '0042',
            paintingDataTitle: 'Copper Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Copper Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0042-1': 'images\0042\0042-1.jpg',
            }
        },

        '0041': {
            metaTitle: 'Golden Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Golden Skull',
            paintingUrlNum: '0041',
            paintingDataTitle: 'Golden Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Golden Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0041-1': 'images\0041\0041-1.jpg',
            }
        },

        '0040': {
            metaTitle: 'Harper Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Harper Skull',
            paintingUrlNum: '0040',
            paintingDataTitle: 'Harper Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Harper Skull',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0040-1': 'images\0040\0040-1.jpg',
            }
        },

        '0039': {
            metaTitle: 'Shoot Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Shoot Skull',
            paintingUrlNum: '0039',
            paintingDataTitle: 'Shoot Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Shoot Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0039-1': 'images\0039\0039-1.jpg',
            }
        },

        '0038': {
            metaTitle: 'Bloody Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Bloody Skull',
            paintingUrlNum: '0038',
            paintingDataTitle: 'Bloody Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Bloody Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0038-1': 'images\0038\0038-1.jpg',
            }
        },


        '0037': {
            metaTitle: 'Pink Bullet Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Pink Bullet Skull',
            paintingUrlNum: '0037',
            paintingDataTitle: 'Pink Bullet Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '29,7 cm',
            paintingDimensionsHeight: '42 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Pink Bullet Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0037-1': 'images\0037\0037-1.jpg',
            }
        },

        '0036': {
            metaTitle: 'Pink Flow',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Pink Flow',
            paintingUrlNum: '0036',
            paintingDataTitle: 'Pink Flow',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Pink Flow',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0036-1': 'images\0036\0036-1.jpg',
            }
        },

        '0035': {
            metaTitle: 'India Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, India Skull',
            paintingUrlNum: '0035',
            paintingDataTitle: 'India Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'India Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0035-1': 'images\0035\0035-1.jpg',
            }
        },

        '0034': {
            metaTitle: 'Clown Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Clown Skull',
            paintingUrlNum: '0034',
            paintingDataTitle: 'Clown Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Clown Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0034-1': 'images\0034\0034-1.jpg',
            }
        },

        '0033': {
            metaTitle: 'Solar Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Solar Skull',
            paintingUrlNum: '0033',
            paintingDataTitle: 'Solar Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Solar Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0033-1': 'images\0033\0033-1.jpg',
            }
        },

        '0032': {
            metaTitle: 'Volatile Skull',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Volatile Skull',
            paintingUrlNum: '0032',
            paintingDataTitle: 'Volatile Skull',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Volatile Skull',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior. Druga część dyptyku z serii "Volatile".',
            paintingImages: {
                '0032-1': 'images\0032\0032-1.jpg',
            }
        },

        '0031': {
            metaTitle: 'Volatile',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Volatile',
            paintingUrlNum: '0031',
            paintingDataTitle: 'Volatile',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Volatile',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior.',
            paintingImages: {
                '0031-1': 'images\0031\0031-1.jpg',
                '0031-2': 'images\0031\0031-2.jpg',
            }
        },

        '0030': {
            metaTitle: 'Wings',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Wings',
            paintingUrlNum: '0030',
            paintingDataTitle: 'Wings',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '50 cm',
            paintingDimensionsHeight: '50 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Wings',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior. Zainspirowany anielskimi skrzydłami.',
            paintingImages: {
                '0030-1': 'images\0030\0030-1.jpg',
            }
        },

        '0029': {
            metaTitle: 'Dragonfly',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Dragonfly',
            paintingUrlNum: '0029',
            paintingDataTitle: 'Dragonfly',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Dragonfly',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior. Zainspirowany owadem ważką oraz pokazem Aleksandra McQueena  Plato\'s Atlantis.',
            paintingImages: {
                '0029-1': 'images\0029\0029-1.jpg',
            }
        },

        '0028': {
            metaTitle: 'Galactus',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Galactus',
            paintingUrlNum: '0028',
            paintingDataTitle: 'Galactus',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '42 cm',
            paintingDimensionsHeight: '59,4 cm',
            paintingYearOfCreation: '2019',    
            paintingTitle: 'Galactus',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca zainspirowana zdjęciem rentgenowskim wykonana akrylem na papierze w nawiązaniu do wystawy i cyklu Interior. Zainspirowany zdjęciem kosmosu.',
            paintingImages: {
                '0028-1': 'images\0028\0028-1.jpg',
            }
        },
        
        '0027': {
            metaTitle: 'Ableton',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Ableton',
            paintingUrlNum: '0027',
            paintingDataTitle: 'Ableton',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '101 cm',
            paintingDimensionsHeight: '134 cm',
            paintingYearOfCreation: '2018',    
            paintingTitle: 'Ableton',
            paintingStatus: 'Available ',
            paintingDescription: 'Ableton jest pracą wykonaną na wystawę Interior. Za inspirację do wykonania pracy posłużyło zdjęcie rentgenowskie czaszki, które stało się abstrakcyjną wariacją oryginału. Ableton to pewnego rodzaju sprzęt muzyczny, oprogramowanie,  wykorzystywane w muzyce elektronicznej, techno do mixowania dźwięków. Praca jest pewnego rodzaju hołdem dla muzyki techno, poniekąd jak cała wystawa Interio. Praca zalaminowana przez odpowiednie oświetlenie uzyskuje wymiar trójwymiarowy.',
            paintingImages: {
                '0027-1': 'images\0027\0027-1.jpg',
                '0027-2': 'images\0027\0027-2.jpg',
            }
        },

        '0026': {
            metaTitle: 'Wonderland',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Wonderland',
            paintingUrlNum: '0026',
            paintingDataTitle: 'Wonderland',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '101 cm',
            paintingDimensionsHeight: '107 cm',
            paintingYearOfCreation: '2018',    
            paintingTitle: 'Wonderland',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca Wonderland jest wykonana również na wystawę Interior. Zainspirowana jest główną pracą i zdjęciem plakatowym, będącym motywem przewodnim wystawy. Symbolizuje cudowny, magiczny, życzeniowy świat. Jest zalaminowana, co przy odpowiednim oświetleniu daje efekt trójwymiarowości.',
            paintingImages: {
                '0026-1': 'images\0026\0026-1.jpg',
            }
        },

        '0025': {
            metaTitle: 'Smoq',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Smoq',
            paintingUrlNum: '0025',
            paintingDataTitle: 'Smoq',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '100 cm',
            paintingDimensionsHeight: '100 cm',
            paintingYearOfCreation: '2018',    
            paintingTitle: 'Smoq',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca powstała specjalnie na wystawę Interior. Słowo smoq to gra słów można ją interpretować jako: "Smoq" mistyczne zwierzę przedstawione z lotu ptaka. "Smoq" zielony dym  którym niejednokrotnie ludzkość  wypełniała swoje płuca. Projekt zainspirowany zdjęciem rentgenowskim płuc. Zalaminowany, odpowiednio oświetlony sprawia wrażenie lekko trójwymiarowego.',
            paintingImages: {
                '0025-1': 'images\0025\0025-1.jpg',
                '0025-2': 'images\0025\0025-2.jpg',
            }
        },

        '0024': {
            metaTitle: 'DNA',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, DNA',
            paintingUrlNum: '0024',
            paintingDataTitle: 'DNA',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '100 cm',
            paintingDimensionsHeight: '200 cm',
            paintingYearOfCreation: '2018',    
            paintingTitle: 'DNA',
            paintingStatus: 'Available ',
            paintingDescription: 'Instalacja artystyczna pod tytułem DNA. Nawiązującą swoim charakterem do cyklu Interior. Stanowiąca metaforyczne odniesienie do dna czyli symbolicznego kodu w którym wszystko jest zapisane.',
            paintingImages: {
                '0024-1': 'images\0024\0024-1.jpg',
                '0024-2': 'images\0024\0024-2.jpg',
                '0024-3': 'images\0024\0024-3.jpg',
                '0024-4': 'images\0024\0024-4.jpg',
                '0024-5': 'images\0024\0024-5.jpg',
                '0024-6': 'images\0024\0024-6.jpg',
                '0024-7': 'images\0024\0024-7.jpg',
                '0024-8': 'images\0024\0024-8.jpg',
                '0024-9': 'images\0024\0024-9.jpg',
            }
        },

        '0023': {
            metaTitle: 'Sieć',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Sieć',
            paintingUrlNum: '0023',
            paintingDataTitle: 'Sieć',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '100 cm',
            paintingDimensionsHeight: '200 cm',
            paintingYearOfCreation: '2018',    
            paintingTitle: 'Sieć',
            paintingStatus: 'Sold',
            paintingDescription: 'Instalacja artystyczna pod tytułem Sieć. Składająca się z pomalowanych pojedynczych zdjęć rentgenowskich łącznie stanowiących całość. Praca będąca metaforą doznań, przeżyć, uczuć, muzycznych, wizualnych, erotycznych stanowiących wewnętrzny interior nas samych.',
            paintingImages: {
                '0023-1': 'images\0023\0023-1.jpg',
                '0023-2': 'images\0023\0023-2.jpg',
                '0023-3': 'images\0023\0023-3.jpg',
            }
        },

        '0022': {
            metaTitle: 'Interior',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Interior',
            paintingUrlNum: '0022',
            paintingDataTitle: 'Interior',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '',
            paintingDimensionsHeight: '',
            paintingYearOfCreation: '2018',    
            paintingTitle: 'Interior',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca z cyklu „Interior”.',
            paintingImages: {
                '0022-1': 'images\0022\0022-1.jpg',
                '0022-2': 'images\0022\0022-2.jpg',
                '0022-3': 'images\0022\0022-3.jpg',
                '0022-4': 'images\0022\0022-4.jpg',
                '0022-5': 'images\0022\0022-5.jpg',
                '0022-6': 'images\0022\0022-6.jpg',
                '0022-7': 'images\0022\0022-7.jpg',
                '0022-8': 'images\0022\0022-8.jpg',
                '0022-9': 'images\0022\0022-9.jpg',
                '0022-10': 'images\0022\0022-10.jpg',
                '0022-11': 'images\0022\0022-11.jpg',
                '0022-12': 'images\0022\0022-12.jpg',
                '0022-13': 'images\0022\0022-13.jpg',
                '0022-14': 'images\0022\0022-14.jpg',
                '0022-15': 'images\0022\0022-15.jpg',
                '0022-16': 'images\0022\0022-16.jpg',
                '0022-17': 'images\0022\0022-17.jpg',
                '0022-18': 'images\0022\0022-18.jpg',
                '0022-19': 'images\0022\0022-19.jpg',
                '0022-20': 'images\0022\0022-20.jpg',
                '0022-21': 'images\0022\0022-21.jpg',
                '0022-22': 'images\0022\0022-22.jpg',
                '0022-23': 'images\0022\0022-23.jpg',
                '0022-24': 'images\0022\0022-24.jpg',
                '0022-25': 'images\0022\0022-25.jpg',
            }
        },

        '0021': {
            metaTitle: 'EGGistence',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, EGGistence',
            paintingUrlNum: '0021',
            paintingDataTitle: 'EGGistence',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '70 cm',
            paintingDimensionsHeight: '100 cm',
            paintingYearOfCreation: '2018',    
            paintingTitle: 'EGGistence',
            paintingStatus: 'Sold',
            paintingDescription: 'Obraz wykonany techniką kolażu z wykorzystaniem opiłków metalu, płótna i farby olejnej. Opiłki metalu przytwierdzone za pośrednictwem specjalistycznego kleju. Pracę charakteryzują różnorodne struktury farby Abstrakcyjne ujęcie jaja, bytu biologicznego oraz abstrakcji, która w nim zachodzi. Obraz podpisany zamalowany po bokach nie wymaga ramy.',
            paintingImages: {
                '0021-1': 'images\0021\0021-1.jpg',
                '0021-2': 'images\0021\0021-2.jpg',
                '0021-3': 'images\0021\0021-3.jpg',
                '0021-4': 'images\0021\0021-4.jpg',
                '0021-5': 'images\0021\0021-5.jpg',
                '0021-6': 'images\0021\0021-6.jpg',
                '0021-7': 'images\0021\0021-7.jpg',
                '0021-8': 'images\0021\0021-8.jpg',
                '0021-9': 'images\0021\0021-9.jpg',
            }
        },

        '0020': {
            metaTitle: 'Monstrancja',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Monstrancja',
            paintingUrlNum: '0020',
            paintingDataTitle: 'Monstrancja',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '70 cm',
            paintingDimensionsHeight: '100 cm',
            paintingYearOfCreation: '2018',    
            paintingTitle: 'Monstrancja',
            paintingStatus: 'Available ',
            paintingDescription: 'Obraz fakturowy wykonany techniką kolażu z wykorzystaniem opiłków metalu, płótna i farby olejnej. Opiłki metalu pochodzą z procesu skrawania ze skrawarki i przytwierdzone są do płótna za pomocą specjalistycznego kleju. Użyto farby olejnej oraz werniksu zabezpieczającego. Boki obrazu są pomalowane więc obraz nadaje się do powieszenia i nie wymaga ramy. Obraz jest matowy z błyszczącymi elementami. Praca jest sygnowana i podpisana na odwrocie. Abstrakcyjne ujęcie przedmiotu  wykorzystywanego w Kościele jakim jest Monstrancja, który pomimo blasku pozostaje ciemny i pełen cieni w środku. Fotografia robiona z lampą błyskową.',
            paintingImages: {
                '0020-1': 'images\0020\0020-1.jpg',
                '0020-2': 'images\0020\0020-2.jpg',
                '0020-3': 'images\0020\0020-3.jpg',
                '0020-4': 'images\0020\0020-4.jpg',
                '0020-5': 'images\0020\0020-5.jpg',
                '0020-6': 'images\0020\0020-6.jpg',
                '0020-7': 'images\0020\0020-7.jpg',
                '0020-8': 'images\0020\0020-8.jpg',
            }
        },

        '0019': {
            metaTitle: 'Czarny miód',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Czarny miód',
            paintingUrlNum: '0019',
            paintingDataTitle: 'Czarny miód',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '70 cm',
            paintingDimensionsHeight: '100 cm',
            paintingYearOfCreation: '2017',    
            paintingTitle: 'Czarny miód',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca wykonana techniką mieszaną, z wykorzystaniem farby olejnej, papieru oraz płótna. Obraz abstrakcyjny stanowi kolaż bądź asamblaż stworzony z różnych elementów. Nawiązuje do plastra miodu ukazanego w symbolicznym, mrocznym, apokaliptycznym, ujęciu, będącym jednocześnie przestrogą braku poszanowania życia z naturą jak i abstrakcyjną wariacją na temat struktury plastra miodu. Praca jest sygnowana na odwrocie, boki ma częściowo zamalowane i nie wymaga ramy, zawerniksowana.',
            paintingImages: {
                '0019-1': 'images\0019\0019-1.jpg',
                '0019-2': 'images\0019\0019-2.jpg',
                '0019-3': 'images\0019\0019-3.jpg',
                '0019-4': 'images\0019\0019-4.jpg',
                '0019-5': 'images\0019\0019-5.jpg',
                '0019-6': 'images\0019\0019-6.jpg',
                '0019-7': 'images\0019\0019-7.jpg',
                '0019-8': 'images\0019\0019-8.jpg',
            }
        }, 

        '0018': {
            metaTitle: 'Czaszki',
            metaDescription: '',
            metaKeywords: 'Structuralist, Interior, Czaszki',
            paintingUrlNum: '0018',
            paintingDataTitle: 'Czaszki',
            paintingDataAuthor: 'Interior',
            paintingDimensionsWidth: '29,7 cm',
            paintingDimensionsHeight: '42 cm',
            paintingYearOfCreation: '2017',    
            paintingTitle: 'Czaszki',
            paintingStatus: 'Sold',
            paintingDescription: 'Czaszki to projekt zainspirowany zdjęciem rentgenowskim, otrzymanym po prześwietleniu głowy. Maszyna do wykonywania rentgena stała się kolejnym sprzętem, który mogłem przełożyć na działania artystyczne, tym samym dołączając do ją do grona, wtryskarek, skrawarek, tokarek. Otworzyło to także nowy rozdział w zainteresowaniach artystycznych - popartem i zapoczątkowało cykl Interior. Zdjęcie autobiograficzne.',
            paintingImages: {
                '0018-1': 'images\0018\0018-1.jpg',
                '0018-2': 'images\0018\0018-2.jpg',
                '0018-3': 'images\0018\0018-3.jpg',
                '0018-4': 'images\0018\0018-4.jpg',
                '0018-5': 'images\0018\0018-5.jpg',
                '0018-6': 'images\0018\0018-6.jpg',
                '0018-7': 'images\0018\0018-7.jpg',
                '0018-8': 'images\0018\0018-8.jpg',
                '0018-9': 'images\0018\0018-9.jpg',
                '0018-10': 'images\0018\0018-10.jpg',
            }
        }, 

        '0017': {
            metaTitle: 'Źródło',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Źródło',
            paintingUrlNum: '0017',
            paintingDataTitle: 'Źródło ',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '46 cm',
            paintingDimensionsHeight: '55 cm',
            paintingYearOfCreation: '2017',    
            paintingTitle: 'Źródło',
            paintingStatus: 'Available ',
            paintingDescription: 'Obraz fakturowy wykonany z opiłków metalu pochodzących ze skrawarki z procesu skrawania, grubo lanej czarnej farby olejnej oraz farb olejnych sztalugowych. Czarny element pracy jest nawiązaniem z do mistycznego źródła, otchłani, przejścia. Jest tez pewnym symbolem niepokoju łączącego wszystkie obrazy, w których czarny element występuje. Podpisany na odwrocie.',
            paintingImages: {
                '0017-1': 'images\0017\0017-1.jpg',
                '0017-2': 'images\0017\0017-2.jpg',
                '0017-3': 'images\0017\0017-3.jpg',
                '0017-4': 'images\0017\0017-4.jpg',
                '0017-5': 'images\0017\0017-5.jpg',
                '0017-6': 'images\0017\0017-6.jpg',
                '0017-7': 'images\0017\0017-7.jpg',
                '0017-8': 'images\0017\0017-8.jpg',
                '0017-9': 'images\0017\0017-9.jpg',
                '0017-10': 'images\0017\0017-10.jpg',
            }
        }, 

        '0016': {
            metaTitle: 'Filtry',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Filtry',
            paintingUrlNum: '0016',
            paintingDataTitle: 'Filtry ',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '21 cm',
            paintingDimensionsHeight: '29,7 cm',
            paintingYearOfCreation: '2017',    
            paintingTitle: 'Filtry',
            paintingStatus: 'Available ',
            paintingDescription: 'Filtry to praca kolaż na którą składają się 4 odrębne prace. Składają się na nią prostokątne tekturowe podkładki, które były wykorzystywane jako podkładki na farbę przy malowaniu  obrazów strukturalnych oraz filtry fotograficzne otrzymane od jednego z operatorów na Camerimage w Bydgoszczy przytwierdzone za pomocą kleju. Praca podpisana na odwrocie.',
            paintingImages: {
                '0016-1': 'images\0016\0016-1.jpg',
                '0016-2': 'images\0016\0016-2.jpg',
                '0016-3': 'images\0016\0016-3.jpg',
                '0016-4': 'images\0016\0016-4.jpg',
                '0016-5': 'images\0016\0016-5.jpg',
                '0016-6': 'images\0016\0016-6.jpg',
                '0016-7': 'images\0016\0016-7.jpg',
                '0016-8': 'images\0016\0016-8.jpg',
                '0016-9': 'images\0016\0016-9.jpg',
                '0016-10': 'images\0016\0016-10.jpg',
            }
        }, 

        '0015': {
            metaTitle: 'Embrion',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Embrion',
            paintingUrlNum: '0015',
            paintingDataTitle: 'Embrion ',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '46 cm',
            paintingDimensionsHeight: '55 cm',
            paintingYearOfCreation: '2016',    
            paintingTitle: 'Embrion',
            paintingStatus: 'Available ',
            paintingDescription: 'Obraz fakturowy, wykonany techniką kolażu. Składa się z plastikowych elementów pochodzących z wtryskarki jednej z fabryk bydgoskich. Elementy zostały przytwierdzone za pośrednictwem specjalistycznego kleju i zabezpieczone werniksem. Poza tym została użyta grubo lana farba olejna. Tytułowy embrion jest ukazany jako symboliczny twór,  który niezależnie od wszystkiego kształtuje się we własnym królestwie. Praca sygnowana podpisana na odwrocie bez możliwości wykonania kopii.',
            paintingImages: {
                '0015-1': 'images\0015\0015-1.jpg',
                '0015-2': 'images\0015\0015-2.jpg',
                '0015-3': 'images\0015\0015-3.jpg',
                '0015-4': 'images\0015\0015-4.jpg',
                '0015-5': 'images\0015\0015-5.jpg',
                '0015-6': 'images\0015\0015-6.jpg',
                '0015-7': 'images\0015\0015-7.jpg',
                '0015-8': 'images\0015\0015-8.jpg',
                '0015-9': 'images\0015\0015-9.jpg',
                '0015-10': 'images\0015\0015-10.jpg',
            }
        }, 

        '0014': {
            metaTitle: 'Insomnia',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Insomnia',
            paintingUrlNum: '0014',
            paintingDataTitle: 'Insomnia',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '46 cm',
            paintingDimensionsHeight: '55 cm',
            paintingYearOfCreation: '2016',    
            paintingTitle: 'Insomnia',
            paintingStatus: 'Available ',
            paintingDescription: 'Insomnia oznacza stan niewystarczającej długości snu lub niezadowalającej jego jakość. Jest to bezsenność. Jest to ciemność z przebłyskami światła. Na obraz składa się masa plastyczna przypominająca wosk, a w rzeczywistości  jest to masa powstała jako ubytek tworzywa z wtryskarek w jednej z bydgoskich fabryk. Elementy plastikowe zostały przytwierdzone do płótna za pomocą specjalistycznego kleju.  Elementy plastikowe zostały zabezpieczone lakierem. Na obraz została naniesiona gruba warstwa czarnej farby olejnej i polakierowana. Praca ma zamalowane boki i nie wymaga ramy.  Jest sygnowana i podpisana na odwrocie. ',
            paintingImages: {
                '0014-1': 'images\0014\0014-1.jpg',
                '0014-2': 'images\0014\0014-2.jpg',
                '0014-3': 'images\0014\0014-3.jpg',
                '0014-4': 'images\0014\0014-4.jpg',
                '0014-5': 'images\0014\0014-5.jpg',
                '0014-6': 'images\0014\0014-6.jpg',
                '0014-7': 'images\0014\0014-7.jpg',
                '0014-8': 'images\0014\0014-8.jpg',
                '0014-9': 'images\0014\0014-9.jpg',
                '0014-10': 'images\0014\0014-10.jpg',
            }
        }, 

        '0013': {
            metaTitle: 'Brainboom',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Brainboom',
            paintingUrlNum: '0013',
            paintingDataTitle: 'Brainboom',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '46 cm',
            paintingDimensionsHeight: '55 cm',
            paintingYearOfCreation: '2016',    
            paintingTitle: 'Brainboom',
            paintingStatus: 'Sold',
            paintingDescription: 'Brainboom jest nawiązaniem do pracy Heartboom. Jest to wybuch mózgu, a raczej,  personifikacja fantazji, wyobraźni, którą ten mózg tworzy. Obraz symbolizujący zmianę, radość pozytywną ekspresję. Praca jest wykonana z wielu elementów industrialnych pochodzących z procesów skrawania oraz wtryskarek, a także materiałów organicznych jak zasuszone owoce i kości. Praca sygnowana podpisana na odwrocie.',
            paintingImages: {
                '0013-1': 'images\0013\0013-1.jpg',
                '0013-2': 'images\0013\0013-2.jpg',
                '0013-3': 'images\0013\0013-3.jpg',
                '0013-4': 'images\0013\0013-4.jpg',
                '0013-5': 'images\0013\0013-5.jpg',
                '0013-6': 'images\0013\0013-6.jpg',
                '0013-7': 'images\0013\0013-7.jpg',
                '0013-8': 'images\0013\0013-8.jpg',
            }
        }, 

        '0012': {
            metaTitle: 'Nenufary',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Nenufary',
            paintingUrlNum: '0012',
            paintingDataTitle: 'Nenufary',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '70 cm',
            paintingDimensionsHeight: '100 cm',
            paintingYearOfCreation: '2015',    
            paintingTitle: 'Nenufary',
            paintingStatus: 'Available ',
            paintingDescription: 'Wariacja na temat obrazów Clouda Moneta o tematyce "Nenufary" i interpretacja utworu Björk "Black Lake". Obraz fakturowy wykonany techniką mieszaną za pomocą kolażu. Składa się z opiłków metal pochodzących z procesu skrawania, przytwierdzonych do płótna za pomocą specjalistycznego kleju, zasuszonych części australijskiej rośliny, Przytwierdzonych również za pomocą specjalistycznego kleju, grubo lanej czarnej farby olejnej oraz werniksu zabezpieczającego obraz. Boki obrazu są zamalowane co sprawia, iż nie potrzebuje on ramy. Praca jest sygnowana i podpisana na odwrocie. Obraz jest  lekko połyskujący z błyszczącymi elementami. Podświetlony od tyłu ukazuje inne kolory niż w normalnej odsłonie.',
            paintingImages: {
                '0012-1': 'images\0012\0012-1.jpg',
                '0012-2': 'images\0012\0012-2.jpg',
                '0012-3': 'images\0012\0012-3.jpg',
                '0012-4': 'images\0012\0012-4.jpg',
                '0012-5': 'images\0012\0012-5.jpg',
                '0012-6': 'images\0012\0012-6.jpg',
                '0012-7': 'images\0012\0012-7.jpg',
                '0012-8': 'images\0012\0012-8.jpg',
                '0012-9': 'images\0012\0012-9.jpg',
                '0012-10': 'images\0012\0012-10.jpg',
                '0012-11': 'images\0012\0012-11.jpg',
            }
        }, 

        '0011': {
            metaTitle: 'Czarny świt',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Czarny świt',
            paintingUrlNum: '0011',
            paintingDataTitle: 'Czarny świt',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '70 cm',
            paintingDimensionsHeight: '100 cm',
            paintingYearOfCreation: '2015',    
            paintingTitle: 'Czarny świt',
            paintingStatus: 'Available ',
            paintingDescription: '"Czarny świt w krwistej barwie coraz mocniej mnie przeraża..." Autor nieznany<br><br>Najlepszy do charakteryzacji tej pracy jest powyższy opis, na który natrafiłem przypadkowo w internecie", który poprzez swoją wyrazistość stał się podwaliną do powstania pracy. Obraz fakturowy wykonany na płótnie ma zamalowane boki dzięki czemu nie wymaga ramy. Jest wykonany z opiłków metalu pochodzących z procesu skrawania ze skrawarki, przytwierdzonych do płótna za pomocą specjalistycznego kleju. Poza tym użyta została farba olejna oraz werniks zabezpieczający. Praca sygnowana i  podpisana na odwrocie obrazu. Powierzchnia matowa  z połyskliwymi elementami. Asamblaż, structural collage.',
            paintingImages: {
                '0011-1': 'images\0011\0011-1.jpg',
                '0011-2': 'images\0011\0011-2.jpg',
                '0011-3': 'images\0011\0011-3.jpg',
                '0011-4': 'images\0011\0011-4.jpg',
                '0011-5': 'images\0011\0011-5.jpg',
                '0011-6': 'images\0011\0011-6.jpg',
                '0011-7': 'images\0011\0011-7.jpg',
            }
        }, 

        '0010': {
            metaTitle: 'Heartboom',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Heartboom',
            paintingUrlNum: '0010',
            paintingDataTitle: 'Heartboom',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '46 cm',
            paintingDimensionsHeight: '55 cm',
            paintingYearOfCreation: '2014',    
            paintingTitle: 'Heartboom',
            paintingStatus: 'Sold',
            paintingDescription: 'Heartboom oznacza dosłownie wybuch serca pod wpływem pewnych doznań, uczuć, emocji, przeżyć. Jest to pewien rodzaj wyzwolenia emocjonalnego. Obraz jest wykonany techniką asamblażu. Składa się z masy plastycznej przypominającej wosk, a będącej w rzeczywistości wypływem plastikowego tworzywa z wtryskarek, pochodzących z jednej z bydgoskich fabryk. Obraz jest sygnowany, podpisany na odwrocie.',
            paintingImages: {
                '0010-1': 'images\0010\0010-1.jpg',
                '0010-2': 'images\0010\0010-2.jpg',
                '0010-3': 'images\0010\0010-3.jpg',
                '0010-4': 'images\0010\0010-4.jpg',
                '0010-5': 'images\0010\0010-5.jpg',
                '0010-6': 'images\0010\0010-6.jpg',
                '0010-7': 'images\0010\0010-7.jpg',
                '0010-8': 'images\0010\0010-8.jpg',
            }
        }, 

        '0009': {
            metaTitle: 'Ant(y)-man',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Ant(y)-man',
            paintingUrlNum: '0009',
            paintingDataTitle: 'Ant(y)-man',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '54 cm',
            paintingDimensionsHeight: '73 cm',
            paintingYearOfCreation: '2014',    
            paintingTitle: 'Ant(y)-man',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca wykonana techniką kolażu. Zastosowana została srebrna farba olejna grubo kładziona oraz przymocowane ulane elementy, pochodzące z maszyny wtryskarka. Obraz posiada elementy wypukłe 3D przedstawionej postaci. Nawiązuje do początków swojego powstania czyli  fabryki która współcześnie często odczłowiecza naszą naturę sprowadzając nas do istot człeko - podobnych, robotów lub w tym wypadku mrówek pracujących jak w gnieździe. Obraz podpisany sygnowany na odwrocie.',
            paintingImages: {
                '0009-1': 'images\0009\0009-1.jpg',
                '0009-2': 'images\0009\0009-2.jpg',
                '0009-3': 'images\0009\0009-3.jpg',
                '0009-4': 'images\0009\0009-4.jpg',
                '0009-5': 'images\0009\0009-5.jpg',
                '0009-6': 'images\0009\0009-6.jpg',
            }
        }, 

        '0008': {
            metaTitle: 'Anturium',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Anturium',
            paintingUrlNum: '0008',
            paintingDataTitle: 'Anturium ',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '40 cm',
            paintingDimensionsHeight: '60 cm',
            paintingYearOfCreation: '2013',    
            paintingTitle: 'Anturium ',
            paintingStatus: 'Available ',
            paintingDescription: 'Obraz fakturowy, kolaż, a właściwie asamblaż. Do wykonania pracy został użyty czarny siateczkowaty materiał, fioletowy kruszony metal pochodzący z procesu skrawania oraz czarna i fioletowa farba olejna. Elementy  zostały przytwierdzone za pomocą specjalistycznego kleju do płótna. Symboliką nawiązuje do Anturium. Kruszony materiał pochodzi z bydgoskiej fabryki jest symbolicznym sercem obrazu, dzięki któremu czarny organizm żyje. Obraz sygnowany podpisany na odwrocie.',
            paintingImages: {
                '0008-1': 'images\0008\0008-1.jpg',
                '0008-2': 'images\0008\0008-2.jpg',
                '0008-3': 'images\0008\0008-3.jpg',
                '0008-4': 'images\0008\0008-4.jpg',
                '0008-5': 'images\0008\0008-5.jpg',
                '0008-6': 'images\0008\0008-6.jpg',
                '0008-7': 'images\0008\0008-7.jpg',
            }
        }, 
        
        '0007': {
            metaTitle: 'Aberracja',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Aberracja',
            paintingUrlNum: '0007',
            paintingDataTitle: 'Aberracja',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '100 cm',
            paintingDimensionsHeight: '120 cm',
            paintingYearOfCreation: '2008',    
            paintingTitle: 'Aberracja',
            paintingStatus: 'Sold',
            paintingDescription: 'Obraz powstał w starej fabryce-lakierni w Bydgoszczy w której kiedyś pracowałem podczas farbowania i lakierowania innych przedmiotów. Kolaż powstał z połączenia płyty kartonowej wykorzystywanej jako podkładka w lakierni, ciętego kruszonego metalu i farby olejnej oraz płótna. Na powierzchni pracy można doszukać się wiele śladów z przeszłości w postaci plam, chlapnięć, zadrapań. Łączy w sobie ducha przeszłości, w której się narodził oraz przyszłości stając się współczesnym obrazem. Obraz jest sygnowany i podpisany na odwrocie.',
            paintingImages: {
                '0007-1': 'images\0007\0007-1.jpg',
                '0007-2': 'images\0007\0007-2.jpg',
                '0007-3': 'images\0007\0007-3.jpg',
                '0007-4': 'images\0007\0007-4.jpg',
                '0007-5': 'images\0007\0007-5.jpg',
                '0007-6': 'images\0007\0007-6.jpg',
                '0007-7': 'images\0007\0007-7.jpg',
                '0007-8': 'images\0007\0007-8.jpg',
            }
        }, 

        '0006': {
            metaTitle: 'Dion',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Dion',
            paintingUrlNum: '0006',
            paintingDataTitle: 'Dion',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '70 cm',
            paintingDimensionsHeight: '110 cm',
            paintingYearOfCreation: '2008',    
            paintingTitle: 'Dion',
            paintingStatus: 'Sold',
            paintingDescription: 'Historia obrazu jest iście industrialna gdyż powstał on w starej fabryce-lakierni w Bydgoszczy w której kiedyś pracowałem podczas farbowania i lakierowania innych przedmiotów. Praca powstała z dwóch części: płyty kartonowej oraz płótna. Dodatkowo została wykorzystana farba olejna w różnych kolorach i warstwach na płycie kartonowej. Udział swój w powstaniu pracy miała maszyna wykorzystywana do mieszania farby. Mieszając farbę dokonywała rozbryzgu na podkładkę, która teraz stanowi główny trzon obrazu. Na pracy widać ślady lakieru, będącego jednym z podstawowych materiałów stosowanych w lakierni.',
            paintingImages: {
                '0006-1': 'images\0006\0006-1.jpg',
                '0006-2': 'images\0006\0006-2.jpg',
                '0006-3': 'images\0006\0006-3.jpg',
                '0006-4': 'images\0006\0006-4.jpg',
                '0006-5': 'images\0006\0006-5.jpg',
            }
        }, 

        '0005': {
            metaTitle: 'RCD 500',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, RCD 500',
            paintingUrlNum: '0005',
            paintingDataTitle: 'RCD 500',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '54 cm',
            paintingDimensionsHeight: '74 cm',
            paintingYearOfCreation: '2008',    
            paintingTitle: 'RCD 500',
            paintingStatus: 'Sold',
            paintingDescription: 'Kolaż powstały podczas pracy w fabryce - lakierni w Bydgoszczy. Część kartonowa wykorzystywana także podczas lakierowania i malowania detali w lakierni przytwierdzona do płótna i pokryta warstwami farby olejnej i pastelami. Obraz zmienia częściowo barwy w zależności od rodzaju oświetlenia. Wyrażenie RCD 500 symbolicznie nawiązuję do podkładek kartonowych wykorzystywanych w lakierni ale równie dobrze może oznaczać daleką, nieodkrytą nam jeszcze galaktykę. Obraz sygnowany podpisany na odwrocie.',
            paintingImages: {
                '0005-1': 'images\0005\0005-1.jpg',
                '0005-2': 'images\0005\0005-2.jpg',
                '0005-3': 'images\0005\0005-3.jpg',
                '0005-4': 'images\0005\0005-4.jpg',
                '0005-5': 'images\0005\0005-5.jpg',
                '0005-6': 'images\0005\0005-6.jpg',
            }
        }, 

        '0004': {
            metaTitle: 'SM',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, SM',
            paintingUrlNum: '0004',
            paintingDataTitle: 'SM',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '46 cm',
            paintingDimensionsHeight: '53 cm',
            paintingYearOfCreation: '2007',    
            paintingTitle: 'SM',
            paintingStatus: 'Available ',
            paintingDescription: 'SM oznacza Something mechanical, Stright maschine, strange material. Historia obrazu nawiązuje do klimatu industrialnego, gdyż elementy, które zawiera pochodzą z fabryki. Składa się z opiłków metalu pochodzących ze skrawarki z procesu skrawania oraz ciętego kruszonego fioletowego metalu, przytwierdzonego za pośrednictwem specjalistycznego kleju do drewnianej płyty pilśniowej. Płyta ma nierówny kształt, grubość około 8 mm, poza opiłkami metalu składa się z grubo lanej warstwy srebrnej farby olejnej na tło oraz smoły z procesu smołowania dachu w środku obrazu. Ostre elementy, ciemne barwy jak i nierówne krawędzie pracy nadają jej surowego charakteru. Praca jest sygnowana na odwrocie.',
            paintingImages: {
                '0004-1': 'images\0004\0004-1.jpg',
                '0004-2': 'images\0004\0004-2.jpg',
                '0004-3': 'images\0004\0004-3.jpg',
                '0004-4': 'images\0004\0004-4.jpg',
                '0004-5': 'images\0004\0004-5.jpg',
            }
        }, 

        '0003': {
            metaTitle: 'Flora',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Flora',
            paintingUrlNum: '0003',
            paintingDataTitle: 'Flora',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '40 cm',
            paintingDimensionsHeight: '60 cm',
            paintingYearOfCreation: '2006',    
            paintingTitle: 'Flora',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca wykonana techniką mieszaną przy użyciu kolażu. Zastosowane zostały organiczne materiały roślinne, gruba warstwa farby olejnej, sprayu i kleju. Praca została zrobiona na starej płycie pilśniowej. Roślinne elementy postaci zostały, zawerniksowane i zabezpieczone przed uszkodzeniem, następnie pomalowane i przytwierdzone za pomocą specjalistycznego kleju do płyty pilśniowej. Boki zamalowane o grubości 8 mm. Obraz ukazuje roślinny charakter postaci będącej jednocześnie personifikacją natury, roślinnej bogini. Siły, jaką natura posiada z jednej strony niezwykłej, z drugiej strony szokującej i przerażającej. Sygnowany i podpisany na odwrocie. Bez możliwości wykonania kopii.',
            paintingImages: {
                '0003-1': 'images\0003\0003-1.jpg',
                '0003-2': 'images\0003\0003-2.jpg',
                '0003-3': 'images\0003\0003-3.jpg',
                '0003-4': 'images\0003\0003-4.jpg',
                '0003-5': 'images\0003\0003-5.jpg',
                '0003-6': 'images\0003\0003-6.jpg',          
            }
        }, 

        '0002': {
            metaTitle: 'Krata',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Krata',
            paintingUrlNum: '0002',
            paintingDataTitle: 'Krata',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '40 cm',
            paintingDimensionsHeight: '60 cm',
            paintingYearOfCreation: '2006',    
            paintingTitle: 'Krata',
            paintingStatus: 'Sold',
            paintingDescription: 'Praca wykonana techniką kolażu. Na jej elementy składa się lekko krzywa płyta pilśniowa, sprężyna od starego łóżka przedstawiająca ową kratę, przytwierdzona za pomocą kleju oraz kładzione grubą warstwą farby olejne. Praca zawerniksowana, sygnowana na odwrocie. Puste pola stanowiące przestrzenie po przetarciu się nakładających się na siebie sprężyn symbolizują pewien błąd, wyrwany z kontekstu rzeczywistości. Inspirowana dokumentem  o obozie koncentracyjnym Auschwitz-Birkenau.',
            paintingImages: {
                '0002-1': 'images\0002\0002-1.jpg',
                '0002-2': 'images\0002\0002-2.jpg',
                '0002-3': 'images\0002\0002-3.jpg',
                '0002-4': 'images\0002\0002-4.jpg',
            }
        }, 

        '0001': {
            metaTitle: 'Czarna kobieta',
            metaDescription: '',
            metaKeywords: 'Structuralist, Structural Collage, Czarna kobieta',
            paintingUrlNum: '0001',
            paintingDataTitle: 'Czarna kobieta',
            paintingDataAuthor: 'Structural Collage',
            paintingDimensionsWidth: '40 cm',
            paintingDimensionsHeight: '60 cm',
            paintingYearOfCreation: '2006',    
            paintingTitle: 'Czarna kobieta',
            paintingStatus: 'Available ',
            paintingDescription: 'Praca wykonana na płycie pilśniowej pochodzącej ze starych mebli. Obraz wykonany z tkaniny jutowej znalezionej na strychu w połączeniu z czarnym kruszonym szkłem wykorzystywanym w procesie spawania oraz przyklejonym pyłem pochodzącym ze szlifowania starych ponad 100- letnich dachówek ceramicznych. Elementy przytwierdzone do płyty za pomocą odpowiedniego kleju i zabezpieczone werniksem. Całość pokryta czarną smolistą farbą oraz czerwoną farbą olejną. Wszystkie elementy przedstawione na obrazie łączy zamierzchła przeszłość i przyszłość w postaci wizerunku kobiety. Obraz sygnowany, podpisany na odwrocie. Bez możliwości wykonania kopii.',
            paintingImages: {
                '0001-1': 'images\0001\0001-1.jpg',
                '0001-2': 'images\0001\0001-2.jpg',
                '0001-3': 'images\0001\0001-3.jpg',
                '0001-4': 'images\0001\0001-4.jpg',
                '0001-5': 'images\0001\0001-5.jpg',
            }
        },        
    },

    // EXHIBITIONS
    exhibitions: {
        '0006': {
            exhibitionHeader: 'Exhibition of modern art from the collection of Piotr Fajkis at the Ignacy Mine in the city of Rybnik, Poland',
            exhibitionDate: 'January 2020 – February 2020',
            exhibitionParagraph: `Collection of art by present young and older Polish artists alike, where Michał Król’s piece titled „The Network” was featured.`,
            exhibitionLink1: 'https://www.rybnik.com.pl/wiadomosci,wystawa-sztuki-wspolczesnej-na-ignacym,wia5-3267-43345.html',
            exhibitionLink2: '',
            exhibitionLink3: '',
            exhibitionPoster: './images/exhibitions/WystawaPiotraFajkisa.jpg',
        },

        '0005': {
            exhibitionHeader: 'Jasinski&friends VII – art exhibition at the Gallery „Przy Teatrze Narodowym” in Warsaw',
            exhibitionDate: 'November 2019 – January 2020',
            exhibitionParagraph: `The 7th edition of Jasinski&friends collective art exhibition was organized by Dominik Jasinski in cooperation with the Gallery „Przy Teatrze Narodowym” in Warsaw. There were 26 pieces of polish artists, including paintings, graphics and photography, where three works of Michał Król entitled „Earth Skull”, „Golden Skul” and „Copper Skull” were featured.`,
            exhibitionLink1: 'https://www.facebook.com/events/3070138143000323/',
            exhibitionLink2: '',
            exhibitionLink3: '',
            exhibitionPoster: './images/exhibitions/Jasiński&Friends.jpg',
        },

        '0004': {
            exhibitionHeader: 'Vernisage of „Interior” works at Popart Gallery in Poznan',
            exhibitionDate: '28.10.2018 – 8.11.2018',
            exhibitionParagraph: `The X-ray imaging shows what’s invisible to the naked eye: our inner shell, structure, organic matter, as metaphor for the INTERIOR within ourselves, an emotional landscapes illustrated with various colours representing emotional, musical, physical and erotic experiences. It is also a tribute to electronic techno music, which carries a particle of futurism, darkness, modernity as well as technical and rawness like an X-ray machine, which has become a diagnostic tool of artistic creation.`,
            exhibitionLink1: 'https://www.facebook.com/events/254804431892324/',
            exhibitionLink2: '',
            exhibitionLink3: '',
            exhibitionPoster: './images/exhibitions/InterioPoznań.jpg',
        },

        '0003': {
            exhibitionHeader: '21 st Internation Congress of Environmental Protection Envicon Environment at the MTP Poznań Expo',
            exhibitionDate: 'October 2017 – October 2017',
            exhibitionParagraph: `Congress is a forum for the most important representatives of goverment central and local administration, represetatives of Polish and foreign enterprises, experts in the field of waste management and water waste management, as well as the use of recyclable materials and reasonable environmental and ecological management. As part of the use of recyclable materials and in relation to the ZERO WASTE trend, STRUCTURAL COLLAGE project was featured to show to possibilities of re-using by products of production processes in artistic terms, connecting ART and ZERO WASTE together.`,
            exhibitionLink1: 'https://www.facebook.com/events/1413554982060525/',
            exhibitionLink2: 'https://www.facebook.com/envicon.abrys/posts/1851582358193016',
            exhibitionLink3: '',
            exhibitionPoster: './images/exhibitions/EnviconPoznań.jpg',
        },

        '0002': {
            exhibitionHeader: 'Vernissage STRUCTURAL COLLAGE at Geranium Caffe in Poznań',
            exhibitionDate: 'June 2017 – September 2017',
            exhibitionParagraph: `The vernissage took place in one of the most popular restaurants in Poznań - Geranium Caffe Vege Cousine, presenting artworks that were focusing on the processes of nature in a different context, by showing abstract creations made in interaction of machines with humans.`,
            exhibitionLink1: 'https://www.facebook.com/events/1910549632553265/',
            exhibitionLink2: '',
            exhibitionLink3: '',
            exhibitionPoster: './images/exhibitions/StructuralCollageGerranium.jpg',
        },

        '0001': {
            exhibitionHeader: 'Exhibition and Happening „STRUCTURAL COLLAGE” in Bydgoszcz',
            exhibitionDate: 'March 2017 – May 2017',
            exhibitionParagraph: `The exhibition took place in the 14th branch of the Provincial and Municipal Public Library in the centre if Bydgoszcz. The projects intention was to reach out to ordinary people and to encourage them to interact with modern art. Visitors were also invited to create a great social library collage: library-art-Street. To achieve this, a huge library window was used, in which distinctive colors were arranged, attempting to draw the attention and encourage people to stop and enjoy the arts.`,
            exhibitionLink1: 'https://www.facebook.com/events/290218671399627/',
            exhibitionLink2: '',
            exhibitionLink3: '',
            exhibitionPoster: './images/exhibitions/StructuralCollageBydgoszcz.jpg',
        }
    },

    // BIOGRAPHY
    biography: {
        biographyHeader: 'Biography',
        biographyParagraph: `Michał Król was born in 1984 in the region of Kujawy, Poland. He obtained a master's degree in Pedagogy and Psychology at the Kazimierz Wielki University in Bydgoszcz, Poland. His works are currently divided into two categories: STRUCTURAL COLLAGE with the use of industrial machines, which had helped the creation of structural paintings and INTERIOR illustrating the insight into the interior literally as well as figuratively, by utilizing X-Ray and magnetic resonance imaging. His source of inspiration were factories in Bydgoszcz, where he used to work in his free time and while studying. From there, he has begun using and assembling industrial materials in his works. Its characteristic collage and structural painting show that the materials can be re-used and put in a new and unique, lively context. His style is mainly inspired by structuralism and industrialism portraying the beauty of things that are present in our lives. His admiration for the works of Alberto Burri, Piotr Łakomy Andy Warhol and Hans Rudolf Giger inspired him to create his very own „structural collage” and “interior”. He has travelled to many countries, such as Australia, Swtizerland, Germany and Great Britain. Currently, he lives and works in Poznan, Poland.`
    },

    // CONTACT
    contact: {
        contactHeader: 'Contact',
        contactEmailButton: 'Get in touch with me'
    },

}